version: '3'
services:
    app:
        container_name: Apache_Sample_Project
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: simpleapache
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
        # links:
        #     - mysql

    # mysql:
    #     container_name: MySQL_Sample_Project
    #     image: mysql:5.7
    #     ports:
    #         - 13306:3306
    #     environment:
    #         MYSQL_DATABASE: dbdev
    #         MYSQL_USER: dev
    #         MYSQL_PASSWORD: dev
    #         MYSQL_ROOT_PASSWORD: dev
